add support for syncing to specific repos
woocommerce/woocommerce-github-sync-labels pull request #13
Opened 2021-01-12 15:18 UTC by rrennick

This PR adds 

- support for specifying syncing to one or more specific repos via the command line
- spacing to the terminal output 
- lists the repos as they are processed to aid in troubleshooting when an error occurs

### Testing

- Run the command against an approved or test repo (could be created under a personal account)
```
npm start -- --dry-run --repo organization/repository1
```

2021-01-20 15:57 UTC, claudiosanches requested changes
Works fine, there's just a minor issue in the README.md

2021-01-20 15:57 UTC, claudiosanches commented on README.md
> +| `--repo`            | Sync to this repository. Multiple repositories supported.
```suggestion
| `--repo`            | Sync to this repository. Multiple repositories supported.    |
```

2021-01-25 14:19 UTC, rrennick commented
@claudiosanches Thanks for catching that. I committed your suggestion.

2021-01-25 18:18 UTC, claudiosanches approved these changes
Great work!

2021-01-25 20:52 UTC, merged